name: 'React Scripts evaluator'
description: 'React Scripts evaluator action for Tryber projects'
outputs:
  result:
    description: 'React Scripts unit tests JSON results in base64 format.'
  pr-number:
    description: 'Pull Request number that trigger build.'
runs:
  using: 'docker'
  image: 'Dockerfile'
